### ISSUE TITLE
GnEndpoints Req está apenas dando um console.log(res.data)

### ISSUE THREAD

**Issue by mailonruan** [gerencianet/gn-api-sdk-typescript#3]
Na função **RUN** quando invocada a função **REQ** na finalização da chamada ela apenas está dando um console log e não dando retorno do resultado da requisão

**Comment by jvoliveiraGN** [comment]
Oi @mailonruan tudo bem?
Acabamos de liberar uma atualização corrigindo a tratativa das responses!
Disponível a partir da Release 1.0.5! #4 
Quaisquer dúvidas, estamos à disposição! 😄
