### ISSUE TITLE
Versão 2.0 não possui o método oneStep

### ISSUE THREAD

**Issue by DenisBessa** [gerencianet/gn-api-sdk-typescript#7]
Ei pessoal, primeiro quero agradecer e parabenizar pela SDK, que melhora muito a DevX.

Recentemente fizemos a atualização para a versão 2.0, e o método oneStep parece ter sido retirado.

Para reproduzir, veja este código que funciona perfeitamente na versão 1.0.7:

```
    gerencianet
      .oneStep([], req.body)
      .then((response) => {
        res.status(200).json(response);
      })
      .catch((error) => {
        res.status(400).json(error);
      })
      .done();
```

**Comment by jvoliveiraGN** [comment]
Boa tarde @DenisBessa tudo certo? :)
A versão 2.0 trouxe mudanças consideráveis para a SDK.
O método oneStep foi substituído pelo `createOneStepCharge`
Nos novos exemplos adicionados você encontra o atual funcionamento dos endpoints
